# Generated by Django 2.1.7 on 2019-03-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=256, verbose_name='Media file name')),
                ('width', models.PositiveIntegerField(verbose_name='Media file width')),
                ('height', models.PositiveIntegerField(verbose_name='Media file height')),
                ('size', models.PositiveIntegerField(verbose_name='Media file size')),
                ('path', models.FilePathField(max_length=500, path='C:\\Users\\saber-nyan\\Documents\\Workspace\\Development\\Workspaces\\Python\\gchan\\gchan\\userdata\\fullres', verbose_name='Media file path (fullres)')),
                ('thumbnailPath', models.FilePathField(max_length=500, path='C:\\Users\\saber-nyan\\Documents\\Workspace\\Development\\Workspaces\\Python\\gchan\\gchan\\userdata\\thumb', verbose_name='Media file path (thumbnail)')),
                ('thumbnailWidth', models.PositiveIntegerField(verbose_name='Media file width (thumbnail)')),
                ('thumbnailHeight', models.PositiveIntegerField(verbose_name='Media file height (thumbnail)')),
                ('filetype', models.CharField(choices=[('JPEG', 'jpeg'), ('PNG', 'png'), ('GIF', 'gif'), ('WEBM', 'webm'), ('WEBP', 'webp')], max_length=4, verbose_name='Media file type')),
                ('hash', models.CharField(max_length=128, verbose_name='SHA512 file hash')),
            ],
        ),
    ]
