# Generated by Django 2.1.7 on 2019-04-11 21:44

import api.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_name', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='название')),
                ('description', models.CharField(max_length=100, verbose_name='описание')),
                ('pages', models.PositiveIntegerField(verbose_name='кол-во страниц')),
                ('bump_limit', models.PositiveIntegerField(verbose_name='бамплимит')),
                ('default_name', models.CharField(max_length=64, verbose_name='имя по умолчанию')),
                ('max_file_size', models.PositiveIntegerField(verbose_name='максимальный размер файла (в КБ)')),
                ('max_text_size', models.PositiveIntegerField(verbose_name='максимальное количество символов')),
                ('closed', models.BooleanField(verbose_name='закрыта?')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='создана')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='изменена')),
            ],
            options={
                'verbose_name': 'доска',
                'verbose_name_plural': 'доски',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('hash', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='SHA512')),
                ('filename', models.CharField(max_length=256, verbose_name='имя')),
                ('width', models.PositiveIntegerField(verbose_name='ширина медиа')),
                ('height', models.PositiveIntegerField(verbose_name='высота медиа')),
                ('size', models.PositiveIntegerField(verbose_name='размер')),
                ('content', models.FileField(max_length=256, upload_to=api.models.content_fname, verbose_name='содержимое')),
                ('preview_content', models.FileField(max_length=256, upload_to=api.models.preview_fname, verbose_name='эскиз')),
                ('thumbnailWidth', models.PositiveIntegerField(verbose_name='ширина эскиза')),
                ('thumbnailHeight', models.PositiveIntegerField(verbose_name='высота эскиза')),
                ('filetype', models.CharField(choices=[('JPEG', 'jpg'), ('PNG', 'png'), ('GIF', 'gif'), ('WEBM', 'webm'), ('WEBP', 'webp')], max_length=4, verbose_name='тип')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='создан')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='изменен')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.PositiveIntegerField(verbose_name='ID')),
                ('banned', models.BooleanField(default=False, verbose_name='забанен?')),
                ('warned', models.BooleanField(default=False, verbose_name='предупрежден?')),
                ('text', models.TextField(verbose_name='текст')),
                ('email', models.CharField(blank=True, max_length=64, verbose_name='почта')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='имя')),
                ('subject', models.CharField(blank=True, max_length=64, verbose_name='тема')),
                ('trip_code', models.CharField(blank=True, max_length=64, verbose_name='трипкод')),
                ('op', models.BooleanField(default=False, verbose_name='ОП-флажок')),
                ('created_at', models.DateTimeField(editable=False, verbose_name='создан')),
                ('modified_at', models.DateTimeField(blank=True, editable=False, verbose_name='изменен')),
                ('files', models.ManyToManyField(blank=True, to='api.File', verbose_name='файлы')),
            ],
            options={
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
                'ordering': ['post_id'],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pinned', models.BooleanField(verbose_name='прилеплен')),
                ('closed', models.BooleanField(verbose_name='закрыт')),
                ('last_bump_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='последний бамп')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='api.Board', verbose_name='доска')),
            ],
            options={
                'verbose_name': 'тред',
                'verbose_name_plural': 'треды',
                'ordering': ['-pinned', '-last_bump_time'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.Thread', verbose_name='тред'),
        ),
    ]
