# Generated by Django 2.1.7 on 2019-04-11 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['filename']},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-pinned', '-last_bump_time']},
        ),
        migrations.AddField(
            model_name='thread',
            name='last_bump_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last bump time'),
        ),
    ]
