# Generated by Django 2.1.7 on 2019-03-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-pinned', 'posts__created_at']},
        ),
    ]
