# Generated by Django 2.1.7 on 2019-03-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pinned',
            field=models.BooleanField(default=False, verbose_name='always on top'),
            preserve_default=False,
        ),
    ]
